name: Weekly Status Summary Email

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch: # Allow manual trigger

jobs:
  send-weekly-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Weekly Email API
        run: |
          curl -X GET "${{ secrets.APP_URL }}/api/cron/weekly-status-summary" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
